export const FETCH_RECOMMENDED = "FETCH_RECOMMENDED";
export const FETCH_INTERESTS = "FETCH_INTERESTS";
export const FETCH_FEED = "FETCH_FEED";
export const FETCH_PODCASTS = "FETCH_PODCASTS";
export const REQUEST_PODCASTS = "REQUEST_PODCASTS";
export const RECEIVE_PODCASTS = "RECEIVE_PODCASTS";
export const FETCH_CLIENT = "FETCH_CLIENT";
